version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Map the container port to the host port
    environment:
      NODE_ENV: production
      PORT: 4000
      JWT_SECRET: your_jwt_secret
      DATABASE_URL: your_database_url
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
